AWSTemplateFormatVersion: "2010-09-09"
Description: WBD Martech Assessment - Basic EC2 Infra

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH Key for EC2 access

Resources:
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-00ca570c1b6d79f36 # Amazon Linux 2 (ap-south-1)
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: |
          #!/bin/bash
          set -e

          yum update -y

          # Node + tools
          curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
          yum install -y nodejs git amazon-cloudwatch-agent

          corepack enable
          corepack prepare pnpm@10.25.0 --activate
          npm install -g pm2

          # App
          mkdir -p /opt/app
          chown -R ec2-user:ec2-user /opt/app

          su - ec2-user << 'EOF'
          cd /opt/app
          git clone https://github.com/mrSamDev/event-pipeline-app.git
          cd event-pipeline-app
          pnpm install
          pnpm --filter api build
          pm2 start apps/api/dist/index.js --name wbd-api
          pm2 save
          EOF

Outputs:
  InstancePublicIP:
    Description: EC2 Public IP
    Value: !GetAtt AppInstance.PublicIp
