AWSTemplateFormatVersion: "2010-09-09"
Description: WBD Martech Assessment - Basic EC2 Infra

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH Key for EC2 access

Resources:
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 4000
          ToPort: 4000
          CidrIp: 0.0.0.0/0

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0f58b397bc5c1f2e8 # Amazon Linux 2 (ap-south-1)
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: |
          #!/bin/bash
          set -e

          yum update -y

          # Install Node.js 20
          curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
          yum install -y nodejs git

          # Enable Corepack and pin pnpm
          corepack enable
          corepack prepare pnpm@10.25.0 --activate

          # Verify versions
          node -v
          pnpm -v

          # Install PM2 globally
          npm install -g pm2

          # Create app directory
          mkdir -p /opt/app
          chown -R ec2-user:ec2-user /opt/app

Outputs:
  InstancePublicIP:
    Description: EC2 Public IP
    Value: !GetAtt AppInstance.PublicIp
